// AUTO-GENERATED. Do not edit.
// Generated by etc/scripts/lucide-svg-to-png.ts

/* eslint-disable @typescript-eslint/no-var-requires */
export const assetsMap = {
  "camera": require("./icons/lucide/camera.png"),
  "search": require("./icons/lucide/search.png"),
  "plus": require("./icons/lucide/plus.png"),
  "heart": require("./icons/lucide/heart.png"),
  "eye": require("./icons/lucide/eye.png"),
  "eye-off": require("./icons/lucide/eye-off.png"),
  "search-x": require("./icons/lucide/search-x.png"),
} as const;
export type IconKey = keyof typeof assetsMap;
