// AUTO-GENERATED. Do not edit.
// Generated by etc/scripts/lucide-svg-to-png.ts

export const assetsMap = {
  camera: require('./lucide/camera.png'),
  search: require('./lucide/search.png'),
  plus: require('./lucide/plus.png'),
  heart: require('./lucide/heart.png'),
  eye: require('./lucide/eye.png'),
  'eye-off': require('./lucide/eye-off.png'),
} as const
export type IconKey = keyof typeof assetsMap
